# Generated by Django 4.2.3 on 2023-10-16 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0009_alter_involvedin_id_alter_session_id_alter_user_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="session", name="clip_num", field=models.IntegerField(default=1),
        ),
    ]
