# Generated by Django 4.1.7 on 2023-04-05 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_session_remove_frame_date_created_remove_frame_user_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InvolvedInSession',
            new_name='InvolvedIn',
        ),
        migrations.AddField(
            model_name='coordinate',
            name='name',
            field=models.TextField(default='hey', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coordinate',
            name='score',
            field=models.FloatField(default=0.99, help_text='Enter the confidence score for this coordinate: '),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='session',
            name='description',
            field=models.TextField(default='hi', help_text='Enter description of the session: ', max_length=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='coordinate',
            name='frame',
            field=models.IntegerField(help_text='Enter the frame that this coordinate belongs to: '),
        ),
        migrations.DeleteModel(
            name='Frame',
        ),
    ]
