# Generated by Django 4.1.7 on 2023-04-14 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_coordinate_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='data',
            field=models.TextField(default='hey', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='session',
            name='name',
            field=models.TextField(default='hey', help_text='Enter the name of this session: ', max_length=100),
            preserve_default=False,
        ),
    ]
