# Generated by Django 4.1.7 on 2023-04-16 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0006_session_data_session_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='data',
        ),
    ]
