# Generated by Django 4.1.7 on 2023-06-23 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0008_delete_coordinate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='involvedin',
            name='id',
            field=models.TextField(max_length=200, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='session',
            name='id',
            field=models.TextField(max_length=200, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.TextField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
