# -*- coding: utf-8 -*-
"""processBlazepose.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ikIhGXk09vfXT2qblsi0MxdR6c-KCL-q
"""

import pandas as pd
import numpy as np
import os
#from sklearn.preprocessing import MinMaxScaler
#from sklearn.preprocessing import OneHotEncoder
#from sklearn.model_selection import train_test_split
#import seaborn as sns
#import tensorflow as tf
from google.colab import drive
import pdb
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
import json
#!pip install open3d
#!pip install --upgrade open3d
#import open3d as o3d
#from open3d.pipelines.registration import registration_icp
!pip install ipympl
import ipympl
#%matplotlib widget
from itertools import chain
from sklearn.preprocessing import MinMaxScaler
#from matplotlib.animation import FuncAnimation
from sklearn.cluster import DBSCAN
from scipy.interpolate import interp1d
import warnings
warnings.filterwarnings('ignore')

drive.mount('/content/drive')
os.chdir('/content/drive/My Drive/TCC_Telereha/')

T = pd.read_csv('tpr_test_20240904_blazepose.csv');
mocap = pd.read_csv('test_20240904_vid0_gait1.csv');
mocapHeader = pd.read_csv('test_20240904_vid0_gait1_header_python.csv', delimiter=',', header=None);

# Extract all the markers
markerBool = mocapHeader.iloc[0].str.match('Marker')
markerBool = markerBool.fillna(False)
mocap_header_reduced = mocapHeader.loc[:,markerBool.values]
mocap_reduced = mocap.loc[:,markerBool.values]

#Extract only skeleton positions from all marker positions
markerBool = mocap_header_reduced.iloc[1].str.match('Skeleton')
markerBool = markerBool.fillna(False)
mocap_header_reduced = mocap_header_reduced.loc[:,markerBool.values]
mocap_reduced = mocap_reduced.loc[:,markerBool.values]

mocap_reduced_org = mocap_reduced.copy()

# This file assings vicon joint indicies to the (best fitting) corresponding mediapipe/blazepose joint
vicon2blazepose = pd.read_excel('vicon2blazepose.xlsx')

vicon_marker_list = []
blazepose_marker_list = []
for mocap_header_line in mocap_header_reduced.iloc[1]:
  for index_vicon, row_vicon in vicon2blazepose.iterrows():
    if row_vicon['Vicon Marker'] in mocap_header_line:
      vicon_marker_list.append(row_vicon['Vicon Marker'])
      blazepose_marker_list.append(row_vicon['MediaPipe Index'])
      break
print(vicon_marker_list)
print(blazepose_marker_list)
#All the joints are listed 3 times in the list (3 coordinates) -- only one entry in the list is needed
blazepose_marker_list = blazepose_marker_list[0::3]
vicon_marker_list = vicon_marker_list[0::3]
print(blazepose_marker_list)
print(vicon_marker_list)

# Contains any is used to extract the meta info from the header file
pattern = '|'.join(vicon_marker_list)
contains_any = mocap_header_reduced.iloc[1].str.contains(pattern, case=False, na=False)

mocap_header_reduced.to_csv('mocap_header_reduced.csv', index=False)

#This code block selects the relevant joints from the mocap data and header file
print(mocap_header_reduced.shape)
print(mocap_reduced.shape)
mocap_header_reduced_org = mocap_header_reduced.copy()
mocap_reduced_org = mocap_reduced.copy()
mocap_header_reduced = mocap_header_reduced.loc[:,contains_any[contains_any==True].index]
mocap_reduced = mocap_reduced.loc[:,contains_any.values]
print(mocap_header_reduced.shape)
print(mocap_reduced.shape)

#select the first frame of both sources for comparison
blazepose_first_frame = T.iloc[range(0,33),:]
print(blazepose_first_frame.shape)
mocap_first_frame = mocap_reduced.iloc[0]
print(mocap_first_frame.shape)

# plot the first frame of the ML-Model output (mediapipe)
from google.colab import output
output.enable_custom_widget_manager()
fig = plt.figure()
ax = fig.add_subplot(111, projection='3d')
ax.scatter(blazepose_first_frame[['PosX']],blazepose_first_frame[['PosY']],blazepose_first_frame[['PosZ']], c='b', marker='o')

# Add labels
ax.set_xlabel('X axis')
ax.set_ylabel('Y axis')
ax.set_zlabel('Z axis')
ax.set_aspect('equal')
ax.grid(True)

blazepose_first_frame_org = blazepose_first_frame.copy()

# this removes markers from the mediapipe data which do not have corresponding vicon markers
blazepose_first_frame = blazepose_first_frame.iloc[blazepose_marker_list].reset_index(drop=True)

blazepose_first_frame

def calculate_angle(a, b, c):
    """
    calculate a joint angle based on the 3 input joints
    :param a: first joint
    :param b: second joint
    :param c: third joint
    :return: angle in degrees
    """
    # Define the 3D coordinates of the points
    if len(a.shape)==2:
      A = np.array([a['PosX'], a['PosY'], a['PosZ']])
      B = np.array([b['PosX'], b['PosY'], b['PosZ']])
      C = np.array([c['PosX'], c['PosY'], c['PosZ']])
      A = A.transpose()[0]
      B = B.transpose()[0]
      C = C.transpose()[0]
    else:
      A = np.array(a)
      B = np.array(b)
      C = np.array(c)
    try:
      AB = B - A
      BC = C - B
    except:
      print(A)
      print(B)
      print(C)
      pdb.set_trace()
    # Calculate the dot product of AB and BC
    dot_product = np.dot(AB, BC)

    # Calculate the magnitudes of AB and BC
    magnitude_AB = np.linalg.norm(AB)
    magnitude_BC = np.linalg.norm(BC)

    # Calculate the angle in radians and then convert to degrees
    angle_rad = np.arccos(dot_product / (magnitude_AB * magnitude_BC))
    angle_deg = np.degrees(angle_rad)
    return angle_deg

def calculate_angle_2d(v1, v2):
    dot_product = np.dot(v1, v2)
    norm_v1 = np.linalg.norm(v1)
    norm_v2 = np.linalg.norm(v2)
    # Calculate the angle in radians and then convert to degrees
    angle_radians = np.arccos(dot_product / (norm_v1 * norm_v2))
    angle_degrees = np.degrees(angle_radians)
    return angle_degrees

def angles_in_plane(A, B, C, plane):
    """
    Calculate the angle between two vectors in a plane.
    :param a: first joint
    :param b: second joint
    :param c: third joint
    :param plane: the plane in which to calculate
    :return: angle in degrees
    """
    if len(A.shape)==2:
      A = np.array([A['PosX'], A['PosY'], A['PosZ']])
      B = np.array([B['PosX'], B['PosY'], B['PosZ']])
      C = np.array([C['PosX'], C['PosY'], C['PosZ']])
      A = A.transpose()[0]
      B = B.transpose()[0]
      C = C.transpose()[0]
    else:
      A = np.array(A)
      B = np.array(B)
      C = np.array(C)
    if plane == 'xy':
        A_proj = A[:2]  # Discard z-coordinate
        B_proj = B[:2]
        C_proj = C[:2]
    elif plane == 'xz':
        A_proj = A[[0, 2]]  # Discard y-coordinate
        B_proj = B[[0, 2]]
        C_proj = C[[0, 2]]
    elif plane == 'yz':
        A_proj = A[1:]  # Discard x-coordinate
        B_proj = B[1:]
        C_proj = C[1:]

    # Create vectors AB and BC in the plane
    AB = B_proj - A_proj
    BC = C_proj - B_proj

    # Calculate the angle between vectors AB and BC
    angle = calculate_angle_2d(AB, BC)
    return angle

def get_mediapipe_marker_positions(data_in,def_in,this_joint):
  """
  get the coordinates of the mediapipe markers for a given joint
  """
  anker1 = def_in[this_joint]['Anker1']
  joint = def_in[this_joint]['ActualJoint']
  anker2 = def_in[this_joint]['Anker2']
  anker1_coordinates = data_in.loc[data_in.ind == anker1]
  joint_coordinates = data_in.loc[data_in.ind == joint]
  anker2_coordinates = data_in.loc[data_in.ind == anker2]
  return anker1_coordinates, joint_coordinates, anker2_coordinates
def get_vicon_marker_positions(data_in,header,def_in,this_joint):
  """
  get the coordinates of the vicon markers for a given joint
  """
  anker1 = def_in[this_joint]['Anker1']
  joint = def_in[this_joint]['ActualJoint']
  anker2 = def_in[this_joint]['Anker2']
  matching_columns_anker1 = [header.columns.get_loc(col) for col in header.columns if anker1 in str(header.loc[1, col])]
  matching_columns_joint = [header.columns.get_loc(col) for col in header.columns if joint in str(header.loc[1, col])]
  matching_columns_anker2 = [header.columns.get_loc(col) for col in header.columns if anker2 in str(header.loc[1, col])]
  anker1_coordinates = data_in.iloc[matching_columns_anker1]
  joint_coordinates = data_in.iloc[matching_columns_joint]
  anker2_coordinates = data_in.iloc[matching_columns_anker2]
  # If there is a missing marker, try to use an alternative marker
  # This alternative is specified in the JSON file
  if (len(anker1_coordinates) == 0 or np.isnan(anker1_coordinates).any()) and def_in[this_joint]['AltAnker1'] != "":
    anker1 = def_in[this_joint]['AltAnker1']
    matching_columns_anker1 = [header.columns.get_loc(col) for col in header.columns if anker1 in str(header.loc[1, col])]
    anker1_coordinates = data_in.iloc[matching_columns_anker1]
  if (len(anker2_coordinates) == 0 or np.isnan(anker2_coordinates).any()) and def_in[this_joint]['AltAnker2'] != "":
    anker2 = def_in[this_joint]['AltAnker2']
    matching_columns_anker2 = [header.columns.get_loc(col) for col in header.columns if anker2 in str(header.loc[1, col])]
    anker2_coordinates = data_in.iloc[matching_columns_anker2]
  return anker1_coordinates, joint_coordinates, anker2_coordinates

def get_vicon_marker_positions1(data_in,header,def_in,this_joint):
  pdb.set_trace()
  anker1 = def_in[this_joint]['Anker1']
  joint = def_in[this_joint]['ActualJoint']
  anker2 = def_in[this_joint]['Anker2']
  matching_columns_anker1 = [header.columns.get_loc(col) for col in header.columns if anker1 in str(header.loc[1, col])]
  matching_columns_joint = [header.columns.get_loc(col) for col in header.columns if joint in str(header.loc[1, col])]
  matching_columns_anker2 = [header.columns.get_loc(col) for col in header.columns if anker2 in str(header.loc[1, col])]
  anker1_coordinates = data_in.iloc[matching_columns_anker1]
  joint_coordinates = data_in.iloc[matching_columns_joint]
  anker2_coordinates = data_in.iloc[matching_columns_anker2]
  if (len(anker1_coordinates) == 0 or np.isnan(anker1_coordinates).any()) and def_in[this_joint]['AltAnker1'] != "":
    anker1 = def_in[this_joint]['AltAnker1']
    matching_columns_anker1 = [header.columns.get_loc(col) for col in header.columns if anker1 in str(header.loc[1, col])]
    anker1_coordinates = data_in.iloc[matching_columns_anker1]
  if len(anker2_coordinates) == 0 or np.isnan(anker2_coordinates).any():
    anker2 = def_in[this_joint]['AltAnker2']
    matching_columns_anker2 = [header.columns.get_loc(col) for col in header.columns if anker2 in str(header.loc[1, col])]
    anker2_coordinates = data_in.iloc[matching_columns_anker2]
  return anker1_coordinates, joint_coordinates, anker2_coordinates

# Open and read the JSON file
with open('mediapipeAngleDefinition.json', 'r') as file:
    mediapipe_angle_definition = json.load(file)
with open('viconAngleDefinition.json', 'r') as file:
    vicon_angle_definition = json.load(file)
joints = ['RightKneeAngle','LeftKneeAngle','LeftShoulderAngle','RightShoulderAngle','LeftElbowAngle','RightElbowAngle','LeftHipAngle','RightHipAngle','LeftAnkleAngle','RightAnkleAngle']

"""Resample vicon data"""

#This shows the length of the two data series
print(T.shape[0]/33)
print(mocap_reduced_org.shape[0])
mocap_new = mocap_reduced_org[0:2000]
T_new = T[0:19800]
print(mocap_new.shape[0]/100)
print(T_new.shape[0]/33)

# very rudementary approach of resampling the data to the same sampling rate
time_100hz = np.linspace(0, 20, 2000)  # time for 100 Hz array
time_30hz = np.linspace(0, 20, 600)   # time for 30 Hz array
df_30hz = pd.DataFrame(index=time_30hz, columns=mocap_new.columns)
for column in mocap_new.columns:
    interpolator = interp1d(mocap_new.index, mocap_new[column], kind='linear')  # Interpolator for each column
    df_30hz[column] = interpolator(time_30hz)
mocap_30hz = df_30hz

# This code block creates a dataframe which has the following parameters for a given
# joint (in the joints list):
# Mediapipe Frame: the number of the frame of the mediapipe result
# Vicon Frame: the number of the frame of the vicon data
# for every Mediapipe frame i assumed 3 vicon frames due to the difference in the sampling rate
# mediapipe angle: angle of the joint based on mediapipe result
# vicon angle: angle of the joint based on vicon data
# AngleDifference: difference between mediapipe and vicon angle
# Joint: name of the current joint
# AngleDifferenceMeanOverSameFrame: mean difference between the angles over all 3 vicon frames per mediapipe frame

blazepose_first_frame = T.iloc[range(0,33),:]
mediapipe_angle_list = []
vicon_angle_list = []
rows = []
df = pd.DataFrame(columns=['MediapipeFrame', 'ViconFrame', 'MediapipeAngle','ViconAngle','AngleDifference','Joint'])
for this_joint in joints: # iterate over the joints list
  for i in range(0,10): # only look at the first 10 mediapipe frames (just for testing)
    this_blazepose_frame = T.iloc[range(0+i*33,33+i*33+i),:] # select all the joints for the current mediapipe frame

    # get the coordinates of that joint for that frame
    mediapipe_anker1_coordinates, mediapipe_joint_coordinates, mediapipe_anker2_coordinates = get_mediapipe_marker_positions(this_blazepose_frame,mediapipe_angle_definition,this_joint)
    mediapipe_angle = calculate_angle(mediapipe_anker1_coordinates, mediapipe_joint_coordinates, mediapipe_anker2_coordinates)
    mediapipe_angle_list.append(mediapipe_angle)

    for j in range(i*3,i*3+3): # iterate over the corresponding vicon frames
      this_mocap_frame = mocap_reduced_org.iloc[j]
      #get the vicon joint positions
      vicon_anker1_coordinates, vicon_joint_coordinates, vicon_anker2_coordinates = get_vicon_marker_positions(this_mocap_frame,mocap_header_reduced_org,vicon_angle_definition,this_joint)
      if len(vicon_anker1_coordinates)==117: # apperently something should not be 117
        vicon_angle_list.append(np.nan)
      else:
        # calculate the angle
        vicon_angle = calculate_angle(vicon_anker1_coordinates, vicon_joint_coordinates, vicon_anker2_coordinates)
        vicon_angle_list.append(vicon_angle)

      #create a row with the previously described parameters and append it to a list
      row = {'MediapipeFrame':i,'ViconFrame':j,'MediapipeAngle':mediapipe_angle,'ViconAngle':vicon_angle,'AngleDifference':abs(mediapipe_angle-vicon_angle),'Joint':this_joint}
      rows.append(row)

# create a dataframe out of this list
df = pd.DataFrame(rows)
expanded_means = []

# calculate the mean of the difference over the 3 vicon frames per mediapipe frame
for this_joint in joints:
  this_df = df.loc[df['Joint'] == this_joint]
  block_size = 3
  arr = this_df['AngleDifference'].to_numpy()
  means= arr.reshape(-1, 3).mean(axis=1)
  expanded_means.append(np.repeat(means, block_size))

df['AngleDifferenceMeanOverSameFrame'] = list(chain.from_iterable(expanded_means))
df.to_excel('angle_difference.xlsx', index=False)

df

def plot_angle_difference_2d_projection(blazepose_df,frame_num_blazepose,mediapipe_angle_definition, joints):
  """
  plot function for the angles in a 2d projection
  """
  fig, ax = plt.subplots(1, 3, figsize=(15, 5),subplot_kw={'projection': '3d'})
  for this_joint in joints:
    this_blazepose_frame = blazepose_df.iloc[range(0+frame_num_blazepose*33,33+frame_num_blazepose*33+frame_num_blazepose),:]
    mediapipe_anker1_coordinates, mediapipe_joint_coordinates, mediapipe_anker2_coordinates = get_mediapipe_marker_positions(this_blazepose_frame,mediapipe_angle_definition,this_joint)
    vector1 = mediapipe_anker1_coordinates[['PosX','PosY','PosZ']].values - mediapipe_joint_coordinates[['PosX','PosY','PosZ']].values
    vector2 = mediapipe_anker2_coordinates[['PosX','PosY','PosZ']].values - mediapipe_joint_coordinates[['PosX','PosY','PosZ']].values
    vector1 = vector1[0]
    vector2 = vector2[0]
    cos_theta = np.dot(vector1, vector2) / (np.linalg.norm(vector1) * np.linalg.norm(vector2))
    angle_degrees = np.degrees(np.arccos(cos_theta))
    angle_2d_xy = angles_in_plane(mediapipe_anker1_coordinates, mediapipe_joint_coordinates, mediapipe_anker2_coordinates,'xy')
    angle_2d_xz = angles_in_plane(mediapipe_anker1_coordinates, mediapipe_joint_coordinates, mediapipe_anker2_coordinates,'xz')
    angle_2d_yz = angles_in_plane(mediapipe_anker1_coordinates, mediapipe_joint_coordinates, mediapipe_anker2_coordinates,'yz')

    angle_text_x = mediapipe_joint_coordinates['PosX'].values[0] + 0.5 * (mediapipe_anker1_coordinates['PosX'].values[0] + mediapipe_anker2_coordinates['PosX'].values[0] - 2 * mediapipe_joint_coordinates['PosX'].values[0])
    angle_text_y = mediapipe_joint_coordinates['PosY'].values[0] + 0.5 * (mediapipe_anker1_coordinates['PosY'].values[0] + mediapipe_anker2_coordinates['PosY'].values[0] - 2 * mediapipe_joint_coordinates['PosY'].values[0])
    angle_text_z = mediapipe_joint_coordinates['PosZ'].values[0] + 0.5 * (mediapipe_anker1_coordinates['PosZ'].values[0] + mediapipe_anker2_coordinates['PosZ'].values[0] - 2 * mediapipe_joint_coordinates['PosZ'].values[0])

    ax[0].text(angle_text_x, angle_text_y, angle_text_z, f'{angle_2d_xy:.2f}°', color='red', fontsize=12)
    ax[0].plot([mediapipe_anker1_coordinates['PosX'].values[0], mediapipe_joint_coordinates['PosX'].values[0], mediapipe_anker2_coordinates['PosX'].values[0]],
            [mediapipe_anker1_coordinates['PosY'].values[0], mediapipe_joint_coordinates['PosY'].values[0], mediapipe_anker2_coordinates['PosY'].values[0]],
            [mediapipe_anker1_coordinates['PosZ'].values[0], mediapipe_joint_coordinates['PosZ'].values[0], mediapipe_anker2_coordinates['PosZ'].values[0]],
            marker='o', color='b', label='Line between points')

    mediapipe_angle = calculate_angle(mediapipe_anker1_coordinates, mediapipe_joint_coordinates, mediapipe_anker2_coordinates)


    ax[0].scatter(this_blazepose_frame[['PosX']],this_blazepose_frame[['PosY']],this_blazepose_frame[['PosZ']], c='b', marker='o')

    ax[1].text(angle_text_x, angle_text_y, angle_text_z, f'{angle_2d_yz:.2f}°', color='red', fontsize=12)
    ax[1].plot([mediapipe_anker1_coordinates['PosX'].values[0], mediapipe_joint_coordinates['PosX'].values[0], mediapipe_anker2_coordinates['PosX'].values[0]],
            [mediapipe_anker1_coordinates['PosY'].values[0], mediapipe_joint_coordinates['PosY'].values[0], mediapipe_anker2_coordinates['PosY'].values[0]],
            [mediapipe_anker1_coordinates['PosZ'].values[0], mediapipe_joint_coordinates['PosZ'].values[0], mediapipe_anker2_coordinates['PosZ'].values[0]],
            marker='o', color='b', label='Line between points')

    mediapipe_angle = calculate_angle(mediapipe_anker1_coordinates, mediapipe_joint_coordinates, mediapipe_anker2_coordinates)


    ax[1].scatter(this_blazepose_frame[['PosX']],this_blazepose_frame[['PosY']],this_blazepose_frame[['PosZ']], c='b', marker='o')

    ax[2].text(angle_text_x, angle_text_y, angle_text_z, f'{angle_2d_xz:.2f}°', color='red', fontsize=12)
    ax[2].plot([mediapipe_anker1_coordinates['PosX'].values[0], mediapipe_joint_coordinates['PosX'].values[0], mediapipe_anker2_coordinates['PosX'].values[0]],
            [mediapipe_anker1_coordinates['PosY'].values[0], mediapipe_joint_coordinates['PosY'].values[0], mediapipe_anker2_coordinates['PosY'].values[0]],
            [mediapipe_anker1_coordinates['PosZ'].values[0], mediapipe_joint_coordinates['PosZ'].values[0], mediapipe_anker2_coordinates['PosZ'].values[0]],
            marker='o', color='b', label='Line between points')

    mediapipe_angle = calculate_angle(mediapipe_anker1_coordinates, mediapipe_joint_coordinates, mediapipe_anker2_coordinates)


    ax[2].scatter(this_blazepose_frame[['PosX']],this_blazepose_frame[['PosY']],this_blazepose_frame[['PosZ']], c='b', marker='o')


  # Add labels
  ax[0].set_xlabel('X axis')
  ax[0].set_ylabel('Y axis')
  ax[0].set_zlabel('Z axis')
  ax[0].set_aspect('equal')
  ax[0].view_init(elev=90, azim=-90) # XY Plane

  ax[1].set_xlabel('X axis')
  ax[1].set_ylabel('Y axis')
  ax[1].set_zlabel('Z axis')
  ax[1].set_aspect('equal')
  ax[1].view_init(elev=0, azim=0) #YZ Plane

  ax[2].set_xlabel('X axis')
  ax[2].set_ylabel('Y axis')
  ax[2].set_zlabel('Z axis')
  ax[2].set_aspect('equal')
  ax[2].view_init(elev=0, azim=90) #XZ Plane
  plt.tight_layout()
  plt.show()

def plot_angle_difference_3d_mediapipe(df,frame_num_in,angle_definition, joints):
  """
  plot the mediapipe angles in a 3d plot
  """
  num_plots = frame_num_in
  fig = plt.figure(figsize=(num_plots * 3, 4))
  colors = ["red", "green", "blue", "yellow", "orange", "purple", "pink", "brown", "black", "white", "gray"]
  j = 0
  for frame_num in range(0,frame_num_in):
    i = 0
    ax = fig.add_subplot(1, num_plots, j + 1, projection='3d')  # Create a 3D subplot

    for this_joint in joints:
      this_frame = df.iloc[range(0+frame_num*33,33+frame_num*33+frame_num),:]
      anker1_coordinates, joint_coordinates, anker2_coordinates = get_mediapipe_marker_positions(this_frame,angle_definition,this_joint)
      vector1 = anker1_coordinates[['PosX','PosY','PosZ']].values - joint_coordinates[['PosX','PosY','PosZ']].values
      vector2 = anker2_coordinates[['PosX','PosY','PosZ']].values - joint_coordinates[['PosX','PosY','PosZ']].values
      vector1 = vector1[0]
      vector2 = vector2[0]
      cos_theta = np.dot(vector1, vector2) / (np.linalg.norm(vector1) * np.linalg.norm(vector2))
      angle_degrees = np.degrees(np.arccos(cos_theta))
      angle_text_x = joint_coordinates['PosX'].values[0] + 0.5 * (anker1_coordinates['PosX'].values[0] + anker2_coordinates['PosX'].values[0] - 2 * joint_coordinates['PosX'].values[0])
      angle_text_y = joint_coordinates['PosY'].values[0] + 0.5 * (anker1_coordinates['PosY'].values[0] + anker2_coordinates['PosY'].values[0] - 2 * joint_coordinates['PosY'].values[0])
      angle_text_z = joint_coordinates['PosZ'].values[0] + 0.5 * (anker1_coordinates['PosZ'].values[0] + anker2_coordinates['PosZ'].values[0] - 2 * joint_coordinates['PosZ'].values[0])
      try:
        ax.text(angle_text_x, angle_text_y, angle_text_z, f'{angle_degrees:.2f}°', color='red', fontsize=12)
        ax.plot([anker1_coordinates['PosX'].values[0], joint_coordinates['PosX'].values[0], anker2_coordinates['PosX'].values[0]],
                [anker1_coordinates['PosY'].values[0], joint_coordinates['PosY'].values[0], anker2_coordinates['PosY'].values[0]],
                [anker1_coordinates['PosZ'].values[0], joint_coordinates['PosZ'].values[0], anker2_coordinates['PosZ'].values[0]],
                marker='o', color='b', label='Line between points')

        #pdb.set_trace()
        mediapipe_angle = calculate_angle(anker1_coordinates, joint_coordinates, anker2_coordinates)


        ax.scatter(this_frame[['PosX']],this_frame[['PosY']],this_frame[['PosZ']], c='b', marker='o')
      except:
        pdb.set_trace()
      i += 1
    j += 1
    # Add labels
    ax.set_xlabel('X axis')
    ax.set_ylabel('Y axis')
    ax.set_zlabel('Z axis')
    ax.set_aspect('equal')
    ax.invert_yaxis()
    ax.grid(True)
  #plt.gca().invert_yaxis()
  plt.tight_layout()
  plt.show()

def plot_angle_difference_3d_vicon(df,frame_num_in,angle_definition, joints,mocap_header_reduced_org):
  """
  plot the vicon angles in a 3d plot
  """
  num_plots = frame_num_in
  fig = plt.figure(figsize=(num_plots * 3, 4))
  colors = ["red", "green", "blue", "yellow", "orange", "purple", "pink", "brown", "black", "white", "gray"]
  with warnings.catch_warnings():
    warnings.simplefilter("ignore", category=warnings.WarningMessage)
    j = 0
    for frame_num in range(0,frame_num_in):
      i = 0
      ax = fig.add_subplot(1, num_plots, j + 1, projection='3d')  # Create a 3D subplot

      for this_joint in joints:
        this_frame = df.iloc[frame_num]
        #this_frame = this_frame.replace([np.inf, -np.inf], np.nan).fillna(0)
        anker1_coordinates, joint_coordinates, anker2_coordinates = get_vicon_marker_positions(this_frame,mocap_header_reduced_org,angle_definition,this_joint)
        try:
          vector1 = anker1_coordinates.values - joint_coordinates.values
          vector2 = anker2_coordinates.values - joint_coordinates.values
        except:
          get_vicon_marker_positions1(this_frame,mocap_header_reduced_org,angle_definition,this_joint)
          pdb.set_trace()
          continue
        cos_theta = np.dot(vector1, vector2) / (np.linalg.norm(vector1) * np.linalg.norm(vector2))
        angle_degrees = np.degrees(np.arccos(cos_theta))
        angle_text_x = joint_coordinates[0] + 0.5 * (anker1_coordinates[0] + anker2_coordinates[0] - 2 * joint_coordinates[0])
        angle_text_y = joint_coordinates[1] + 0.5 * (anker1_coordinates[1] + anker2_coordinates[1] - 2 * joint_coordinates[1])
        angle_text_z = joint_coordinates[2] + 0.5 * (anker1_coordinates[2] + anker2_coordinates[2] - 2 * joint_coordinates[2])
        try:
          ax.text(angle_text_x, angle_text_y, angle_text_z, f'{angle_degrees:.2f}°', color=colors[i], fontsize=12)
          ax.plot([anker1_coordinates[0], joint_coordinates[0], anker2_coordinates[0]],
                  [anker1_coordinates[1], joint_coordinates[1], anker2_coordinates[1]],
                  [anker1_coordinates[2], joint_coordinates[2], anker2_coordinates[2]],
                  marker='o', color=colors[i], label='Line between points')

          #pdb.set_trace()
          angle_3d = calculate_angle(anker1_coordinates, joint_coordinates, anker2_coordinates)
          angle_2d_xy = angles_in_plane(anker1_coordinates, joint_coordinates, anker2_coordinates,'xy')
          angle_2d_xz = angles_in_plane(anker1_coordinates, joint_coordinates, anker2_coordinates,'xz')
          angle_2d_yz = angles_in_plane(anker1_coordinates, joint_coordinates, anker2_coordinates,'yz')
          ax.scatter(this_frame[::3],this_frame[1::3],this_frame[2::3], c='b', marker='o')
        except:
          pass
          pdb.set_trace()
        i += 1
      j += 1

      # Add labels
      ax.set_xlabel('X axis')
      ax.set_ylabel('Y axis')
      ax.set_zlabel('Z axis')
      ax.set_aspect('equal')

      ax.grid(True)
    plt.tight_layout()
    plt.show()

# call the plot functions and supress some plot related warnings
import warnings
import logging
logging.getLogger('matplotlib.text').setLevel(logging.ERROR)
plot_angle_difference_3d_vicon(df=mocap_30hz,frame_num_in=20,angle_definition=vicon_angle_definition,joints=joints,mocap_header_reduced_org=mocap_header_reduced_org)
plot_angle_difference_3d_mediapipe(df=T_new,frame_num_in=20,angle_definition=mediapipe_angle_definition,joints=joints)

# plot the mediapipe angles in 3d
plot_angle_difference_3d_mediapipe(df=T,frame_num=1,angle_definition=mediapipe_angle_definition,joints=joints)

# plot the mediapipe angles in a 2d projection
plot_angle_difference_2d_projection(T,1,mediapipe_angle_definition,joints)

# initializing a scaler
scaler = MinMaxScaler()
T.vid_name.unique()

# plotting the coordinates of specific joints over time
joints_of_interest = [11,13,15,23,25,27,31]
for i in joints_of_interest:
  this_T = T[T['ind']==i]
  this_T = this_T[this_T['vid_name']=='test_20240904_vid1_gait1.mp4']
  this_T.reset_index(drop=True, inplace=True)
  x_pos = this_T[['PosX']]
  y_pos = this_T[['PosY']]
  z_pos = this_T[['PosZ']]
  #x_pos = scaler.fit_transform(x_pos)
  #y_pos = scaler.fit_transform(y_pos)
  #z_pos = scaler.fit_transform(z_pos)
  fig, (ax1, ax2, ax3) = plt.subplots(3, 1, figsize=(8, 10))
  fig.suptitle(f'Joint {i}')
  ax1.plot(x_pos)
  ax1.set_title('X-Coordinate')
  ax1.set_ylabel('Abs Position')
  ax1.set_xlabel('Frame')
  ax2.plot(y_pos)
  ax2.set_title('Y-Coordinate')
  ax2.set_ylabel('Abs Position')
  ax2.set_xlabel('Frame')
  ax3.plot(z_pos)
  ax3.set_title('Z-Coordinate')
  ax3.set_ylabel('Abs Position')
  ax3.set_xlabel('Frame')
  #fig.add_subplot(111, projection='3d' ,frame_on=False)
  #plt.tick_params(labelcolor='none', top=False, bottom=False, left=False, right=False)
  plt.tight_layout()
  plt.show()

def remove_outliers_iqr(data):
    """Removes outliers from a NumPy array using the IQR method.

    Args:
        data: NumPy array containing the data.

    Returns:
        NumPy array with outliers removed.
    """
    Q1 = np.percentile(data, 25)
    Q3 = np.percentile(data, 75)
    IQR = Q3 - Q1
    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR
    outlier_mask = (data < lower_bound) | (data > upper_bound)  # Boolean mask for outliers
    return outlier_mask

# Plotting a single joint over time unfiltered (left plot) vs filtered (right plot)

this_T = T[T['ind']==11]
this_T = this_T[this_T['vid_name']=='test_20240904_vid1_gait1.mp4']
this_T.reset_index(drop=True, inplace=True)
x_pos = this_T[['PosX']].values
y_pos = this_T[['PosY']].values
z_pos = this_T[['PosZ']].values
# Create a figure and 3D axis
fig = plt.figure()
fig = plt.figure(figsize=(10, 5))  # Adjust figure size as needed
ax1 = fig.add_subplot(121, projection='3d')  # 1x2 grid, first subplot
ax2 = fig.add_subplot(122, projection='3d')  # 1x2 grid, second subplot

# Update function for the animation
def update1(frame):
    # Update the point's data for the new frame
    point.set_data(x_pos[frame], y_pos[frame])
    point.set_3d_properties(z_pos[frame])
    pdb.set_trace()
    return point,
x_pos = x_pos.flatten()
y_pos = y_pos.flatten()
z_pos = z_pos.flatten()

ax1.plot(x_pos, y_pos, z_pos, label='3D Trajectory')
ax1.scatter(x_pos, y_pos, z_pos, c='b', marker='o')

ax1.set_xlabel('X axis')
ax1.set_ylabel('Y axis')
ax1.set_zlabel('Z axis')

bln_x_pos = remove_outliers_iqr(x_pos)
bln_y_pos = remove_outliers_iqr(y_pos)
bln_z_pos = remove_outliers_iqr(z_pos)
combined_arr = bln_x_pos | bln_y_pos | bln_z_pos
f_x_pos = x_pos[~combined_arr]
f_y_pos = y_pos[~combined_arr]
f_z_pos = z_pos[~combined_arr]

ax2.plot(f_x_pos, f_y_pos, f_z_pos, label='3D Trajectory')
ax2.scatter(f_x_pos, f_y_pos, f_z_pos, c='b', marker='o')
ax2.set_xlabel('X axis')
ax2.set_ylabel('Y axis')
ax2.set_zlabel('Z axis')
plt.tight_layout()
plt.show()
# Create the animation
#ani = FuncAnimation(fig, update1, frames=len(x_pos), interval=10)

dx_pos = np.diff(x_pos)
dy_pos = np.diff(y_pos)
dz_pos = np.diff(z_pos)
bln_dx_pos = remove_outliers_iqr(dx_pos)
bln_dy_pos = remove_outliers_iqr(dy_pos)
bln_dz_pos = remove_outliers_iqr(dz_pos)
combined_d_arr = bln_dx_pos | bln_dy_pos | bln_dz_pos
combined_d_arr = np.insert(combined_d_arr, 0, False)
f_dx_pos = x_pos[~combined_d_arr]
f_dy_pos = y_pos[~combined_d_arr]
f_dz_pos = z_pos[~combined_d_arr]
fig = plt.figure()
ax1 = fig.add_subplot(121, projection='3d')
ax1.plot(f_dx_pos, f_dy_pos, f_dz_pos, label='3D Trajectory')
ax1.scatter(f_dx_pos, f_dy_pos, f_dz_pos, c='b', marker='o')
ax1.set_xlabel('X axis')
ax1.set_ylabel('Y axis')
ax1.set_zlabel('Z axis')
# Show the plot
plt.tight_layout()
plt.show()

# plotting the change in the x coord for a joint over time unfiltered (blue) filtered based on the change of the
# x-coord (yellow) and filtered based on the change of all coord (green)
fig = plt.figure()
ax = fig.add_subplot(111)
ax.plot(dx_pos)
ax.plot(dx_pos[~bln_dx_pos])
this_combined_d_arr = bln_dx_pos | bln_dy_pos | bln_dz_pos
ax.plot(dx_pos[~this_combined_d_arr])
plt.show()

# plotting the change in the y coord for a joint over time unfiltered (blue) filtered based on the change of the
# y-coord (yellow) and filtered based on the change of all coord (green)
fig = plt.figure()
ax = fig.add_subplot(111)
ax.plot(dy_pos)
ax.plot(dy_pos[~bln_dy_pos])
this_combined_d_arr = bln_dx_pos | bln_dy_pos | bln_dz_pos
ax.plot(dy_pos[~this_combined_d_arr])
plt.show()

# plotting the change in the z coord for a joint over time unfiltered (blue) filtered based on the change of the
# z-coord (yellow) and filtered based on the change of all coord (green)

# The z coord shows way more fluctuation in the change (and hence the position) than the y and x coord, probably
# due to the mediapipes estimation of this third dimension

fig = plt.figure()
ax = fig.add_subplot(111)
ax.plot(dz_pos)
ax.plot(dz_pos[~bln_dz_pos])
this_combined_d_arr = bln_dx_pos | bln_dy_pos | bln_dz_pos
ax.plot(dz_pos[~this_combined_d_arr])
plt.show()

# bocplot showing the outliers of the change in the x coord
dx_pos = np.diff(y_pos)
print(dx_pos)
fig = plt.figure()
plt.boxplot(dx_pos)
plt.title('Boxplot of NumPy Array (Matplotlib)')
plt.show()

df[(df['MediapipeFrame']==0) & (df['ViconFrame']==0)]

i=2
print(range(0+i*33,33+i*33))
tmp = T.iloc[range(0+i*33,33+i*33+i),:]
print(tmp.shape)

mocap_header_reduced

"""Registration of mediapipe to mocap data"""

# this defined the mediapipe coordinates as the source of the registration and
# the mocap data to be the target of this transformation
source = blazepose_first_frame[['PosX', 'PosY', 'PosZ']].to_numpy()
mocap_first_frame_reshaped = mocap_first_frame.to_numpy().reshape(24,3)
target = mocap_first_frame_reshaped
#target = target[~np.isnan(target)].reshape(int(target[~np.isnan(target)].shape[0]/3),3)

print(source.shape)
print(target.shape)

source_pcd = o3d.geometry.PointCloud()
target_pcd = o3d.geometry.PointCloud()
# Set the points for the PointClouds
source_pcd.points = o3d.utility.Vector3dVector(source)
target_pcd.points = o3d.utility.Vector3dVector(target)

def calculate_transformation(source, target):
    """
    ICP (iterative closest point) image registration
    register/transform the source to the target
    """
    # Extract corresponding points using indices
    src_points = source
    tgt_points = target

    # Compute centroids
    src_centroid = np.mean(src_points, axis=0)
    tgt_centroid = np.mean(tgt_points, axis=0)

    # Center the points
    src_centered = src_points - src_centroid
    tgt_centered = tgt_points - tgt_centroid

    # Compute the covariance matrix
    covariance_matrix = np.dot(src_centered.T, tgt_centered)

    # Singular Value Decomposition
    U, _, Vt = np.linalg.svd(covariance_matrix)

    # Compute rotation
    R = np.dot(Vt.T, U.T)

    # Ensure a proper rotation matrix (det(R) should be 1)
    if np.linalg.det(R) < 0:
        Vt[2, :] *= -1
        R = np.dot(Vt.T, U.T)

    # Compute translation
    t = tgt_centroid - np.dot(R, src_centroid)

    return R, t

def apply_transformation(points, R, t):
    return np.dot(points, R.T) + t

def icp1(source, target, max_iterations=10, tolerance=1e-4):
    # Initialize the transformation
    current_source = source.copy()

    for i in range(max_iterations):
        # Calculate transformation
        R, t = calculate_transformation(current_source, target)

        # Apply transformation
        current_source = apply_transformation(current_source, R, t)

        # Compute distances between corresponding points
        distances = np.linalg.norm(current_source - target, axis=1)
        mean_error = np.mean(distances)

        # Print the mean error for monitoring
        print(f"Iteration {i+1}, Mean Error: {mean_error:.6f}")
        # Plot source and target during this iteration
        fig = plt.figure()
        ax = fig.add_subplot(111, projection='3d')
        ax.scatter3D(target[:, 0], target[:, 1], target[:, 2], c='r', label='Target')
        ax.scatter3D(current_source[0, :], current_source[1, :], current_source[2, :], c='b', label='Source')
        ax.set_title(f'Iteration {i+1}')
        ax.legend()
        #ax.set_aspect('equal')
        plt.show()
        # Check convergence
        if mean_error < tolerance:
            print("Converged.")
            break

    return current_source, R, t
def icp2(source, target, max_iterations=10, tolerance=1e-4):
    # Initialize the transformation
    current_source = source.copy()

    for i in range(max_iterations):
        # Calculate transformation
        R, t = calculate_transformation(current_source, target)

        # Apply transformation
        current_source = apply_transformation(current_source, R, t)

        # Compute distances between corresponding points
        distances = np.linalg.norm(current_source - target, axis=1)
        mean_error = np.mean(distances)

        # Print the mean error for monitoring
        print(f"Iteration {i+1}, Mean Error: {mean_error:.6f}")
        # Plot source and target during this iteration
        fig = plt.figure()
        ax = fig.add_subplot(111, projection='3d')
        ax.scatter3D(target[:, 0], target[:, 1], target[:, 2], c='r', label='Target')
        ax.scatter3D(current_source[:, 0], current_source[:, 1], current_source[:, 2], c='b', label='Source')
        ax.set_title(f'Iteration {i+1}')
        ax.legend()
        #ax.set_aspect('equal')
        plt.show()
        # Check convergence
        if mean_error < tolerance:
            print("Converged.")
            break

    return current_source, R, t

def normalize_point_cloud(points):
    """Normalizes a point cloud by centering and scaling.

    Args:
        points: NumPy array representing the point cloud.

    Returns:
        normalized_points: Normalized point cloud.
    """
    centroid = np.mean(points, axis=0)
    centered_points = points - centroid
    scale = np.max(np.linalg.norm(centered_points, axis=1))
    normalized_points = centered_points / scale
    return normalized_points

# Perform ICP
threshold = 0.02  # Distance threshold for correspondence
transformation = registration_icp(source_pcd, target_pcd, threshold,
                                                np.eye(4),  # Initial transformation (identity)
                                                o3d.pipelines.registration.TransformationEstimationPointToPoint())
#print(transformation)
nan_indices = np.isnan(source).any(axis=1)
source_no_nan = source[~nan_indices]
target_no_nan = target[~nan_indices]
nan_indices = np.isnan(target).any(axis=1)
source_no_nan = source[~nan_indices]
target_no_nan = target[~nan_indices]
target_no_nan = normalize_point_cloud(target_no_nan)
source_no_nan = normalize_point_cloud(source_no_nan)
print(source_no_nan[:,2])
source_no_nan[:,2] = np.flip(source_no_nan[:,2])
print(source_no_nan[:,2])

# I tried to rotate the array to start at a more favourable position for the ICP

theta = np.radians(90)
rotation_matrix_3d = np.array([
    [np.cos(theta), -np.sin(theta), 0],
    [0, 0, 1],
    [np.sin(theta), np.cos(theta), 0]
])
rotated_arr = source_no_nan @ rotation_matrix_3d.T

# Another rotation attempt
source_no_nan_copy = source_no_nan.copy()
tmp = np.rot90(source_no_nan_copy,k=1, axes=(1, 2))
tmp1 = np.empty(source_no_nan.shape, dtype=float)
tmp1[:,0] = tmp[0,:]
tmp1[:,1] = tmp[1,:]
tmp1[:,2] = tmp[2,:]

print(tmp1)

# plotting the rotated array compared to the original array
fig = plt.figure()
ax = fig.add_subplot(111, projection='3d')
ax.scatter3D(target_no_nan[:, 0], target_no_nan[:, 1], target_no_nan[:, 2], c='r', label='Target')
ax.scatter3D(source_no_nan[:, 0], source_no_nan[:, 1], np.flip(source_no_nan[:, 2],), c='b', label='Source')
ax.scatter3D(rotated_arr[:,0], rotated_arr[:, 1], rotated_arr[:, 2], c='g', label='Source Flipped')
ax.legend()
ax.set_aspect('equal')
plt.show()

# perform the ICP on the rotated array
# Also perfrom the ICP on arrays without NaNs
aligned_source, rotation, translation = icp2(rotated_arr, target_no_nan)
aligned_source, rotation, translation = icp2(source_no_nan, target_no_nan)

# again trying to flip the source
fig = plt.figure()
ax = fig.add_subplot(111, projection='3d')
ax.scatter3D(source_no_nan[:, 0], source_no_nan[:, 1], source_no_nan[:, 2], c='r', label='Target')
ax.scatter3D(source_no_nan_copy[:, 0], source_no_nan_copy[:, 1], np.flip(source_no_nan_copy[:, 2],), c='b', label='Source')
tmp = np.rot90(source_no_nan_copy)
ax.scatter3D(tmp[0,:], tmp[1,:], tmp[2,:], c='g', label='Source')
ax.legend()
ax.set_aspect('equal')
plt.show()

tmp
tmp1 = numpy.empty(shape, dtype=float, order='C', *, device=None, like=None)
tmp1[:,0] = tmp[0,:]

print(tmp.shape)
print(source_no_nan.shape)
tmp1 = np.empty(source_no_nan.shape, dtype=float)
tmp1[:,0] = tmp[0,:]
tmp1[:,1] = tmp[1,:]
tmp1[:,2] = tmp[2,:]

from google.colab import output
output.enable_custom_widget_manager()
fig = plt.figure()
ax = fig.add_subplot(111, projection='3d')
ax.scatter(target_no_nan[:,0],target_no_nan[:,1],target_no_nan[:,2], c='b', marker='o')
#ax.scatter(source_no_nan[:,0],source_no_nan[:,1],source_no_nan[:,2], c='r', marker='o')
source_no_nan_copy = source_no_nan.copy()
# Trim the last element for pairing
columns_to_rotate = source_no_nan_copy[:, [1, 2]]

# Define the 90-degree rotation matrix
rotation_matrix = np.array([[0, -1], [1, 0]])

# Apply the 90-degree rotation to each pair of columns (row-wise)
rotated_columns = columns_to_rotate @ rotation_matrix.T

# Replace the original two columns with the rotated ones
source_no_nan_copy[:, [1, 2]] = rotated_columns

#source_no_nan_copy = np.flip(source_no_nan_copy,axis=(1))
ax.scatter(source_no_nan_copy[:,0],source_no_nan_copy[:,1],source_no_nan_copy[:,2], c='g', marker='x')
#print(source_no_nan)
#print(source_no_nan_copy)
# Add labels
ax.set_xlabel('X axis')
ax.set_ylabel('Y axis')
ax.set_zlabel('Z axis')
ax.set_aspect('equal')
ax.grid(True)

aligned_source, rotation, translation = icp(source_no_nan_copy, target_no_nan)

print(np.asarray(source_pcd.points))
print(np.asarray(target_pcd.points))